spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: "${AUTH_SERVICE_URL}"
              predicates:
                - Path=/auth/**
            - id: protected-service
              uri: "${PROTECTED_SERVICE_URL}"
              predicates:
                - Path=/protected/**
logging:
  level:
    org.springframework: TRACE